### ISSUE TITLE
'Post' object has no attribute 'model'"

### ISSUE THREAD

**Issue by AhmedSalam22** [AhmedSalam22/okuna-api#11]
cannot convert post item to relay 

this doesn't work
`  post_item =  DjangoFilterConnectionField(
        PostType,
        post_uuid = graphene.String(required=True)
    )` 
where this work well
`  post_item =  graphene.Field(
        PostType,
        post_uuid = graphene.String(required=True)
    )`
![image](https://github.com/AhmedSalam22/okuna-api/assets/35177448/71f0634f-fbe1-4584-8c31-25185022ca0f)
![image](https://github.com/AhmedSalam22/okuna-api/assets/35177448/4e1b3819-e394-4b01-9304-55e9c37386e1)

**Comment by raemundo** [comment]
@AhmedSalam22  is this suppose to return one post?
